<a href="https://colab.research.google.com/github/ram0ng1/Ciencia_de_Dados_Aprendizagem_Maquina/blob/main/Unidade2_Analise_e_Ciencia_de_Dados/PythonCienciaDeDados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Manipulação de Dados Tabulares com Pandas
Funções Básicas

In [ ]:
import pandas as pd

cidades = pd.DataFrame(
    [
        ['Paraná', 'Londrina', 575377, 1356.00],
        ['São Paulo', 'São Carlos', 254484, 1508.00],
        ['Santa Catarina', 'Florianópolis', 508826, 1798.00],
        ['Paraná', 'Curitiba', 1963726, 2293.00],
        ['São Paulo', 'Campinas', 1223237, 1710.00]
    ],
    columns=['Estado', 'Cidade', 'Habitantes', 'Salário-Médio']
)

cidades

           Estado         Cidade  Habitantes  Salário-Médio
0          Paraná       Londrina      575377         1356.0
1       São Paulo     São Carlos      254484         1508.0
2  Santa Catarina  Florianópolis      508826         1798.0
3          Paraná       Curitiba     1963726         2293.0
4       São Paulo       Campinas     1223237         1710.0

In [ ]:
cidades.head(2)
cidades.tail(2)
cidades.shape
cidades.info()
cidades.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Estado         5 non-null      object
 1   Cidade         5 non-null      object
 2   Habitantes     5 non-null      int64
 3   Salário-Médio  5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

Index(['Estado', 'Cidade', 'Habitantes', 'Salário-Médio'], dtype='object')

Tipos de Dados com Pandas

In [ ]:
cidades['Salário-Médio'].describe()
cidades.dtypes
cidades.info()
cidades['Habitantes'] = cidades['Habitantes'].astype('float64')

cidades.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Estado         5 non-null      object
 1   Cidade         5 non-null      object
 2   Habitantes     5 non-null      int64
 3   Salário-Médio  5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

Estado            object
Cidade            object
Habitantes       float64
Salário-Médio    float64
dtype: object

Trabalhando com datas

In [ ]:
cidades['Data'] = [
    '3-8-2021',
    '3-9-2021',
    '3-10-2021',
    '3-11-2021',
    '3-12-2021'
]

cidades['Data'] = pd.to_datetime(
    cidades['Data'],
    format='%d-%m-%Y'
)

cidades

cidades['Data'] = cidades['Data'].dt.strftime('%d-%m-%Y')

cidades

           Estado         Cidade  Habitantes  Salário-Médio        Data
0          Paraná       Londrina    575377.0         1356.0  03-08-2021
1       São Paulo     São Carlos    254484.0         1508.0  03-09-2021
2  Santa Catarina  Florianópolis    508826.0         1798.0  03-10-2021
3          Paraná       Curitiba   1963726.0         2293.0  03-11-2021
4       São Paulo       Campinas   1223237.0         1710.0  03-12-2021

Renomeando colunas

In [ ]:
cidades.rename(
    columns={
        'Habitantes': 'N Habitantes',
        'Data': 'Data - Censo'
    },
    inplace=True
)

cidades

           Estado         Cidade  N Habitantes  Salário-Médio Data - Censo
0          Paraná       Londrina      575377.0         1356.0   03-08-2021
1       São Paulo     São Carlos      254484.0         1508.0   03-09-2021
2  Santa Catarina  Florianópolis      508826.0         1798.0   03-10-2021
3          Paraná       Curitiba     1963726.0         2293.0   03-11-2021
4       São Paulo       Campinas     1223237.0         1710.0   03-12-2021

Selecionando linhas e colunas

In [ ]:
cidadesHab = cidades[['N Habitantes', 'Salário-Médio']]

cidadesHab

cidades.loc[[1, 2]]

cidades.iloc[1:3]

cidades.iloc[:, 0:2]

cidades.iloc[1:3, :3]

cidades.iloc[:, [1, 3, 0, 2]]

          Cidade  Salário-Médio          Estado  N Habitantes
0       Londrina         1356.0          Paraná      575377.0
1     São Carlos         1508.0       São Paulo      254484.0
2  Florianópolis         1798.0  Santa Catarina      508826.0
3       Curitiba         2293.0          Paraná     1963726.0
4       Campinas         1710.0       São Paulo     1223237.0

Adicionando e removendo colunas

In [ ]:
cidades.insert(
    2,
    'Sigla',
    ['PR', 'SP', 'SC', 'PR', 'SP']
)

cidades

,Estado,Cidade,Sigla,N Habitantes,Salário-Médio,Data - Censo
0,Paraná,Londrina,PR,575377.0,1356.0,03-08-2021
1,São Paulo,São Carlos,SP,254484.0,1508.0,03-09-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,03-10-2021
3,Paraná,Curitiba,PR,1963726.0,2293.0,03-11-2021
4,São Paulo,Campinas,SP,1223237.0,1710.0,03-12-2021

In [ ]:
cidades.insert(
    2,
    'Sigla-Repetida',
    cidades['Sigla']
)

cidades

,Estado,Cidade,Sigla-Repetida,Sigla,N Habitantes,Salário-Médio,Data - Censo
0,Paraná,Londrina,PR,PR,575377.0,1356.0,03-08-2021
1,São Paulo,São Carlos,SP,SP,254484.0,1508.0,03-09-2021
2,Santa Catarina,Florianópolis,SC,SC,508826.0,1798.0,03-10-2021
3,Paraná,Curitiba,PR,PR,1963726.0,2293.0,03-11-2021
4,São Paulo,Campinas,SP,SP,1223237.0,1710.0,03-12-2021

In [ ]:
cidades = cidades.drop(
    ['Sigla-Repetida'],
    axis=1
)

cidades

,Estado,Cidade,Sigla,N Habitantes,Salário-Médio,Data - Censo
0,Paraná,Londrina,PR,575377.0,1356.0,03-08-2021
1,São Paulo,São Carlos,SP,254484.0,1508.0,03-09-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,03-10-2021
3,Paraná,Curitiba,PR,1963726.0,2293.0,03-11-2021
4,São Paulo,Campinas,SP,1223237.0,1710.0,03-12-2021

Operações Básicas - Consultas

In [ ]:
cidades.query('`Salário-Médio` > 1400.0')

,Estado,Cidade,Sigla,N Habitantes,Salário-Médio,Data - Censo
1,São Paulo,São Carlos,SP,254484.0,1508.0,03-09-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,03-10-2021
3,Paraná,Curitiba,PR,1963726.0,2293.0,03-11-2021
4,São Paulo,Campinas,SP,1223237.0,1710.0,03-12-2021

In [ ]:
cidades.query('Estado == "São Paulo"')

      Estado      Cidade Sigla  N Habitantes  Salário-Médio Data - Censo
1  São Paulo  São Carlos    SP      254484.0         1508.0   03-09-2021
4  São Paulo    Campinas    SP     1223237.0         1710.0   03-12-2021

In [ ]:
cidades.query(
    '`N Habitantes` > 500000 and `N Habitantes` < 1300000'
)

,Estado,Cidade,Sigla,N Habitantes,Salário-Médio,Data - Censo
0,Paraná,Londrina,PR,575377.0,1356.0,03-08-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,03-10-2021
4,São Paulo,Campinas,SP,1223237.0,1710.0,03-12-2021

Operações Básicas - Ordenação

In [ ]:
cidades.sort_values(
    by='Cidade',
    inplace=True
)

cidades

,Estado,Cidade,Sigla,N Habitantes,Salário-Médio,Data - Censo
4,São Paulo,Campinas,SP,1223237.0,1710.0,03-12-2021
3,Paraná,Curitiba,PR,1963726.0,2293.0,03-11-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,03-10-2021
0,Paraná,Londrina,PR,575377.0,1356.0,03-08-2021
1,São Paulo,São Carlos,SP,254484.0,1508.0,03-09-2021

In [ ]:
cidades.sort_values(
    by='Salário-Médio',
    inplace=True
)

cidades

,Estado,Cidade,Sigla,N Habitantes,Salário-Médio,Data - Censo
0,Paraná,Londrina,PR,575377.0,1356.0,03-08-2021
1,São Paulo,São Carlos,SP,254484.0,1508.0,03-09-2021
4,São Paulo,Campinas,SP,1223237.0,1710.0,03-12-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,03-10-2021
3,Paraná,Curitiba,PR,1963726.0,2293.0,03-11-2021

Operações Básicas - Combinando DataFrames

In [ ]:
cidades_salarios = pd.DataFrame(
    [
        ['Paraná', 'Londrina', 1356.00],
        ['São Paulo', 'São Carlos', 1508.00],
        ['Santa Catarina', 'Florianópolis', 1798.00],
        ['Paraná', 'Curitiba', 2293.00],
        ['São Paulo', 'Campinas', 1710.00]
    ],
    columns=['Estado', 'Cidade', 'Salário-Médio']
)

cidades_salarios

           Estado         Cidade  Salário-Médio
0          Paraná       Londrina         1356.0
1       São Paulo     São Carlos         1508.0
2  Santa Catarina  Florianópolis         1798.0
3          Paraná       Curitiba         2293.0
4       São Paulo       Campinas         1710.0

In [ ]:
cidades_pop = pd.DataFrame(
    [
        ['Londrina', 575377],
        ['São Carlos', 254484],
        ['Florianópolis', 508826],
        ['Curitiba', 1963726],
        ['Campinas', 1223237]
    ],
    columns=['Cidade', 'Habitantes']
)

cidades_pop

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826
3       Curitiba     1963726
4       Campinas     1223237

In [ ]:
pd.merge(
    left=cidades_salarios,
    right=cidades_pop,
    on="Cidade"
)

           Estado         Cidade  Salário-Médio  Habitantes
0          Paraná       Londrina         1356.0      575377
1       São Paulo     São Carlos         1508.0      254484
2  Santa Catarina  Florianópolis         1798.0      508826
3          Paraná       Curitiba         2293.0     1963726
4       São Paulo       Campinas         1710.0     1223237

In [ ]:
pd.merge(
    left=cidades_salarios,
    right=cidades_pop,
    on="Cidade",
    how="outer"
)

           Estado         Cidade  Salário-Médio  Habitantes
0       São Paulo       Campinas         1710.0     1223237
1          Paraná       Curitiba         2293.0     1963726
2  Santa Catarina  Florianópolis         1798.0      508826
3          Paraná       Londrina         1356.0      575377
4       São Paulo     São Carlos         1508.0      254484

Operações Básicas - Salvando DataFrames

In [ ]:
cidades_df1 = pd.DataFrame(
    [
        ['Londrina', 575377],
        ['São Carlos', 254484],
        ['Florianópolis', 508826]
    ],
    columns=['Cidade', 'Habitantes']
)

cidades_df1

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826

In [ ]:
cidades_df2 = pd.DataFrame(
    [
        ['Curitiba', 1963726],
        ['Campinas', 1223237]
    ],
    columns=['Cidade', 'Habitantes']
)

cidades_df2

     Cidade  Habitantes
0  Curitiba     1963726
1  Campinas     1223237

In [ ]:
pd.concat(
    [cidades_df1, cidades_df2],
    ignore_index=True
)

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826
3       Curitiba     1963726
4       Campinas     1223237

In [ ]:
cidades.to_csv("my_df.csv", index=False)

In [ ]:
cidades.to_html("my_df.html")

In [ ]:
cidades.to_json("my_df.json")